weekNumber: 28
rule:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-parameters-schema-type-info
    message: Parameter Schema Type
  - code: openapi-parameters-schema-type-string-maxlength-warn
    message: Parameter Schema Type String MaxLength
  - code: openapi-parameters-schema-type-string-minlength-warn
    message: Parameter Schema Type String MinLength
  - code: openapi-parameters-schema-type-string-pattern-warn
    message: Parameter Schema Type String Pattern
  - code: openapi-tags-object-error
    message: Tag Object
  - code: openapi-info-contact-error
    message: Contact Object
  - code: openapi-info-license-error
    message: License Object
  - code: openapi-info-terms-of-service-error
    message: Terms of Service
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-version-in-path-info
    message: Version in Path
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-request-body-on-post-error
    message: Request Body POST
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation ID Camel Case
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: invalid-ref
    message: >-
      ENOENT: no such file or directory, open
      './examples/VirtualNetworkSubnetUsage.json'
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-parameters-description-error
    message: Parameter Description
  - code: openapi-parameters-in-error
    message: Parameters In
  - code: openapi-parameters-name-error
    message: Parameter Name
  - code: openapi-parameters-required-info
    message: Parameter has a required property.
  - code: openapi-parameters-schema-error
    message: Parameter Schema Type
  - code: invalid-ref
    message: >-
      ENOENT: no such file or directory, open
      '../../../../../common-types/resource-management/v5/types.json'
  - code: openapi-parameters-description-error
    message: Parameter Description
  - code: openapi-parameters-in-error
    message: Parameters In
  - code: openapi-parameters-name-error
    message: Parameter Name
  - code: openapi-parameters-required-info
    message: Parameter has a required property.
  - code: openapi-parameters-schema-error
    message: Parameter Schema Type
  - code: openapi-parameters-description-error
    message: Parameter Description
  - code: openapi-parameters-in-error
    message: Parameters In
  - code: openapi-parameters-name-error
    message: Parameter Name
  - code: openapi-parameters-required-info
    message: Parameter has a required property.
  - code: openapi-parameters-schema-error
    message: Parameter Schema Type
  - code: invalid-ref
    message: 'ENOENT: no such file or directory, open ''../../../types/common-types.json'''
  - code: openapi-parameters-name-info
    message: Parameter Name
  - code: openapi-parameters-in-info
    message: Parameters In
  - code: openapi-parameters-required-error
    message: Parameters MUST have a required property.
  - code: openapi-parameters-schema-info
    message: Parameter Schema Type
  - code: openapi-parameters-description-info
    message: Parameter Description
  - code: openapi-response-post-201-status-code-error
    message: POST 201 Status Code
  - code: openapi-response-post-400-status-code-warn
    message: 400 Status Code for POST Responses
  - code: openapi-response-post-404-status-code-warn
    message: 404 Status Code for POST Responses
  - code: openapi-response-post-500-status-code-error
    message: 500 Status Code for POST Responses
  - code: openapi-response-get-default-content-error
    message: Default Content
  - code: openapi-response-get-default-status-code-info
    message: Response Has Default Status Code
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-length-error
    message: Operation Summary Length
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-security-schemes-error
    message: Security Scheme
